// AUTO-GENERATED by `node scripts/public-stories/beds.mjs --upload` — do not
// edit by hand. Empty until the beds have been uploaded; the player hides the
// ambience picker while this map is empty.
export const AMBIENT_BED_URLS: Record<string, string> = {};
