// AUTO-GENERATED by `node scripts/public-stories/beds.mjs --upload` — do not
// edit by hand.
export const AMBIENT_BED_URLS: Record<string, string> = {
  rain: 'https://firebasestorage.googleapis.com/v0/b/yourname-7fc08.firebasestorage.app/o/static-assets%2Fambient-beds%2Frain.mp3?alt=media&token=a5f8d009-ff52-4201-aa5b-a50c39d25814',
  street: 'https://firebasestorage.googleapis.com/v0/b/yourname-7fc08.firebasestorage.app/o/static-assets%2Fambient-beds%2Fstreet.mp3?alt=media&token=288c8d4e-db62-4ed8-8140-98189e158dd9',
  waves: 'https://firebasestorage.googleapis.com/v0/b/yourname-7fc08.firebasestorage.app/o/static-assets%2Fambient-beds%2Fwaves.mp3?alt=media&token=d01a3afd-2bb7-471e-8dfc-1f614471e7f1',
  forest: 'https://firebasestorage.googleapis.com/v0/b/yourname-7fc08.firebasestorage.app/o/static-assets%2Fambient-beds%2Fforest.mp3?alt=media&token=dd1209fa-9f59-4ea8-bd6d-ab8d44abdf7e',
};
