// AUTO-GENERATED by `node scripts/public-stories/beds.mjs --upload` — do not
// edit by hand.
export const AMBIENT_BED_URLS: Record<string, string> = {
  rain: 'https://firebasestorage.googleapis.com/v0/b/yourname-7fc08.firebasestorage.app/o/static-assets%2Fambient-beds%2Frain.mp3?alt=media&token=29701a71-9d6f-4a9c-8440-b04a81201a44',
  street: 'https://firebasestorage.googleapis.com/v0/b/yourname-7fc08.firebasestorage.app/o/static-assets%2Fambient-beds%2Fstreet.mp3?alt=media&token=984e5344-8b54-4718-b49d-db5b457812b7',
  waves: 'https://firebasestorage.googleapis.com/v0/b/yourname-7fc08.firebasestorage.app/o/static-assets%2Fambient-beds%2Fwaves.mp3?alt=media&token=84aee683-4936-486f-8f53-7f1bb6fd1003',
  forest: 'https://firebasestorage.googleapis.com/v0/b/yourname-7fc08.firebasestorage.app/o/static-assets%2Fambient-beds%2Fforest.mp3?alt=media&token=482b2807-5bf2-4b88-acc7-3fae960433fa',
  hum: 'https://firebasestorage.googleapis.com/v0/b/yourname-7fc08.firebasestorage.app/o/static-assets%2Fambient-beds%2Fhum.mp3?alt=media&token=163b20f1-eda3-472c-997d-e2d0b1f28125',
};
