#!/usr/bin/env node
// Universal player ambience — renders the fixed bed loops and (with --upload)
// ships them as app-wide static assets. These beds are the ONLY ambience in
// the app: no personalized/generated ambient sound, and playback defaults to
// none; the player layers the chosen loop under any audio client-side.
//
//   node scripts/public-stories/beds.mjs             render out/beds/*.mp3 (audition locally)
//   node scripts/public-stories/beds.mjs --upload    render + upload to Storage + write
//                                                    constants/ambient-beds.generated.ts
//
// Each loop is 120s and every tremolo period divides 120 exactly, so the loop
// point is phase-continuous. Levels are baked into the files (player plays at
// volume 1): street mirrors the approved not-jealous mix (minus a hair of
// headroom against summed peaks); rain/waves sit clearly audible but under the
// voice; forest is faintest because its hiss shares the whisper's band.

import dotenv from 'dotenv';
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { initializeApp } from 'firebase/app';
import { getAuth, signInWithEmailAndPassword } from 'firebase/auth';
import { getDownloadURL, getStorage, ref, uploadBytes } from 'firebase/storage';
import { askHidden, retryable } from './lib.mjs';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
dotenv.config();
dotenv.config({ path: path.join(__dirname, '../../.env') });

const OUT = path.join(__dirname, 'out', 'beds');
const GENERATED_TS = path.join(__dirname, '../../constants/ambient-beds.generated.ts');
const ADMIN_EMAIL = 'ellepotterhead2006@gmail.com';

const BEDS = {
  rain: 'anoisesrc=colour=pink:sample_rate=44100:amplitude=0.18:d=120,lowpass=f=1400,highpass=f=300,tremolo=f=0.15:d=0.35',
  street: 'anoisesrc=colour=brown:sample_rate=44100:amplitude=0.55:d=120,lowpass=f=300,tremolo=f=0.1:d=0.5,volume=0.8',
  waves: 'anoisesrc=colour=pink:sample_rate=44100:amplitude=0.6:d=120,lowpass=f=850,highpass=f=60,tremolo=f=0.1:d=0.85,volume=0.3',
  forest: 'anoisesrc=colour=pink:sample_rate=44100:amplitude=0.5:d=120,highpass=f=800,lowpass=f=4500,tremolo=f=0.15:d=0.55,volume=0.18',
  // Low hum (first-story walk bed): a faint 65 Hz tone over deep brown rumble.
  // 65 Hz × 120 s = 7800 whole cycles and tremolo 0.1 Hz = 12 periods, so the
  // loop point stays phase-continuous like the others.
  hum: 'sine=frequency=65:sample_rate=44100:d=120,volume=0.10[hs];anoisesrc=colour=brown:sample_rate=44100:amplitude=0.5:d=120,lowpass=f=160,tremolo=f=0.1:d=0.4,volume=0.4[hn];[hs][hn]amix=inputs=2:duration=first:normalize=0,volume=0.85',
};

function render() {
  fs.mkdirSync(OUT, { recursive: true });
  for (const [key, chain] of Object.entries(BEDS)) {
    const out = path.join(OUT, `${key}.mp3`);
    execFileSync('ffmpeg', ['-hide_banner', '-loglevel', 'error', '-y', '-filter_complex', `${chain}[a]`, '-map', '[a]', '-b:a', '128k', out]);
    console.log(`✅ ${path.relative(process.cwd(), out)}`);
  }
}

async function upload() {
  const app = initializeApp({
    apiKey: process.env.FIREBASE_API_KEY,
    authDomain: process.env.FIREBASE_AUTH_DOMAIN,
    projectId: process.env.FIREBASE_PROJECT_ID,
    storageBucket: process.env.FIREBASE_STORAGE_BUCKET,
    messagingSenderId: process.env.FIREBASE_MESSAGING_SENDER_ID,
    appId: process.env.FIREBASE_APP_ID,
  });
  const auth = getAuth(app);
  const password = process.env.YN_ADMIN_PASSWORD || (await askHidden(`Enter password for ${ADMIN_EMAIL}: `));
  const cred = await signInWithEmailAndPassword(auth, ADMIN_EMAIL, password);
  const storage = getStorage(app);
  console.log(`✅ signed in as ${cred.user.uid}`);

  const urls = {};
  for (const key of Object.keys(BEDS)) {
    const buf = fs.readFileSync(path.join(OUT, `${key}.mp3`));
    const fileRef = ref(storage, `static-assets/ambient-beds/${key}.mp3`);
    await retryable(() => uploadBytes(fileRef, buf, { contentType: 'audio/mpeg' }), { label: `upload ${key}` });
    await new Promise((res) => setTimeout(res, 300));
    urls[key] = await getDownloadURL(fileRef);
    console.log(`✅ ${key} → static-assets/ambient-beds/${key}.mp3`);
  }

  const ts = [
    '// AUTO-GENERATED by `node scripts/public-stories/beds.mjs --upload` — do not',
    '// edit by hand.',
    'export const AMBIENT_BED_URLS: Record<string, string> = {',
    ...Object.entries(urls).map(([k, u]) => `  ${k}: '${u}',`),
    '};',
    '',
  ].join('\n');
  fs.writeFileSync(GENERATED_TS, ts, 'utf8');
  console.log(`✅ wrote ${path.relative(process.cwd(), GENERATED_TS)} — rebuild/redeploy the web app to ship the picker.`);
  process.exit(0);
}

render();
if (process.argv.includes('--upload')) {
  await upload();
} else {
  console.log('\nlisten in scripts/public-stories/out/beds/ — then re-run with --upload to ship.');
}
